spring:
  application:
    name: rating-service
server:
  port: 8084


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
  instance:
    preferIpAddress: true


  
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
